version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    entrypoint:
      - /bin/bash
      - -c
      - |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        airflow db init
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true
        airflow webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags/scripts:/opt/airflow/scripts
      - ./credentials:/opt/airflow/credentials
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - DISPLAY=:99
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  scheduler:
    build: .
    entrypoint:
      - /bin/bash
      - -c
      - |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags/scripts:/opt/airflow/scripts
      - ./credentials:/opt/airflow/credentials
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - DISPLAY=:99
    depends_on:
      webserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres-db-volume:
